name: Snyk SAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  sast:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run SAST Scan
        run: snyk code test
