name: Snyk SCA Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  sca:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Dependency Scan
        run: snyk test
