name: DevSecOps Security Pipeline
 
on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:   
  security:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    
# downloads your project's code into the virtual machine so the pipeline can work with it.
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: app
        run: npm install

      ####################################################
      # Build Docker Image
      ####################################################

      - name: Build Docker Image
        run: docker build -t demo-image ./app

      ####################################################
      # Snyk SAST
      ####################################################

      - name: Snyk Code Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
        continue-on-error: true

      ####################################################
      # Snyk SCA
      ####################################################

      - name: Snyk Dependency Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
        continue-on-error: true

      ####################################################
      # Trivy Filesystem Scan
      ####################################################

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
              scan-type: fs
              scan-ref: .
              format: sarif
              output: trivy-fs.sarif
              severity: HIGH,CRITICAL
        continue-on-error: true

      - name: Upload Trivy Filesystem Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs
          
      ####################################################
      # Trivy Secret Scan
      ####################################################

      - name: Trivy Secret Scan
        uses: aquasecurity/trivy-action@master
        with:
              scan-type: fs
              scan-ref: .
              scanners: secret
              format: sarif
              output: trivy-secret.sarif
              continue-on-error: true

      - name: Upload Trivy Secret Results
        uses: github/codeql-action/upload-sarif@v3
        with:
              sarif_file: trivy-secret.sarif
              category: trivy-secret

      ####################################################
        # Trivy Image Scan
      ####################################################

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
                    image-ref: demo-image
                    format: sarif
                    output: trivy-image.sarif
                    severity: HIGH,CRITICAL
                    continue-on-error: true

      - name: Upload Trivy Image Results
        uses: github/codeql-action/upload-sarif@v3
        with:
              sarif_file: trivy-image.sarif
              category: trivy-image
            
      ####################################################
      # Snyk Container Scan
      ####################################################

      - name: Snyk Container Scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: demo-image
          args: --severity-threshold=medium
        continue-on-error: true
